export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS = " GET_POSTS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const GET_COMMENTS = "GET_COMMENTS";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAIL = "GET_POSTS_FAIL";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_POSTS_FAIL";

export const GET_USER_POSTS = "GET_USER_POSTS";
export const GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS";
export const GET_USER_POSTS_FAIL = "GET_POSTS_FAIL";

export const GET_FILTERED_POSTS = "GET_FILTERED_POSTS";
export const GET_SORT_POSTS = "GET_SORT_POSTS";

export const DEL_FILTERED_POSTS = "DEL_FILTERED_POSTS";
export const DEL_SORT_POSTS = "DEL_SORT_POSTS";
